import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<link
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet"
/>
import Navbar from '../components/Layout/Navbar';
import Footer from '../components/Layout/Footer';
import { ThemeProvider } from "next-themes";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
        <div className="flex flex-col min-h-screen">
          {/* Navbar stays at the top */}
          <Navbar />

          {/* Scrollable content */}
          <main className="flex-grow w-full pb-16 pt-[50px] md:pt-[120px]"> 
            {/* add padding-bottom so content doesn't overlap footer */}
            {children}
          </main>

          {/* Fixed Footer */}
          <Footer />
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}


